### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by natalifm** [natalifm/homepage111#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Natalifm998** [comment]
jkgolol;

**Comment by natalifm** [comment]
jl

**Comment by natalifm** [comment]
RÉSUMÉ
— I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by natalifm** [comment]
<h2>RÉSUMÉ</h2>

**Comment by Natalifm998** [comment]
<h2>Résumé</h2>
                                <p>&mdash; I'm the most successful person ever to run for the presidency, by far.
                                    Nobody's ever been more successful than me. I'm the most successful person ever to
                                    run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth
                                    more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you
                                    all know it! Please don't feel so stupid or insecure, it's not your fault.
                                </p>

**Comment by Natalifm998** [comment]
RÉSUMÉ
— I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by Natalifm998** [comment]
•	https://www.fb.com/DonaldTrump
•	realDonaldTrump@whitehouse.gov
•	https://twitter.com/realDonaldTrump
•	https://www.instagram.com/realDonaldTrump/
